name: Auto Update Dice Jobs Excel

on:
  schedule:
    - cron: "*/27 * * * *" # runs for every 27 mins
  workflow_dispatch:

concurrency:
  group: auto-job-update
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
              pip install --upgrade pip
              pip install -r requirements.txt
              
      - name: Run Python Script
        run: |
          python DiceLinks.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add dice_jobs_list.xlsx

          git commit -m "Auto-update: dice_jobs_list.xlsx - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"

          # Fetch latest changes from remote
          git fetch origin main

          # Rebase local changes on top of remote main
          git rebase origin/main

          # Push updated branch
          git push origin main
